[package]
name = "ratelite"
version = "0.0.0-dev"
edition = "2024"

[dependencies]
# window
winit = "0.30.12"
glow = "0.16.0"
glutin = "0.32.3"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"

image = "0.25.9"
fontdue = "0.9.3"